enum data_entries_floats {
	SDBR_FREQUENCY_GHZ,
	SDBR_TEMPERATURE_K,
	SDBR_AEFF_UM,
	SDBR_MAX_DIMENSION_MM,
	SDBR_CABS_M,
	SDBR_CBK_M,
	SDBR_CEXT_M,
	SDBR_CSCA_M,
	SDBR_G,
	SDBR_AS_XY,
	SDBR_NUM_DATA_ENTRIES_FLOATS
};
enum data_entries_ints {
	SDBR_FLAKETYPE,
	//SDBR_SHAPE_ID,
	//SDBR_RUN_ID,
	//SDBR_PFTABLE_ID,
	SDBR_NUM_DATA_ENTRIES_INTS
};
enum data_entries_stats_fields {
	SDBR_S_MIN,
	SDBR_S_MAX,
	SDBR_MEDIAN,
	SDBR_MEAN,
	SDBR_SD,
	SDBR_SKEWNESS,
	SDBR_KURTOSIS,
	SDBR_NUM_DATA_ENTRIES_STATS
};


